#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  5 21:49:45 2018

@author: joykumardas
"""

class Fraction:
    
    def __init__( self , top , bottom ):
        self.numerator , self.denominator = Fraction.reduce( top , bottom )
        
    @staticmethod
    def reduce( numrtr , dnmntr ):
        common = cls.gcd( numrtr , dnmntr )
        return ( self.numerator // common , self.denominator // common )